#!/usr/bin/env bash

echo "----------"
echo "Test 1"
echo "----------"
diff test/2200909C/out1.txt <(./2200909C <test/2200909C/input1.txt)
echo "----------"
echo "Test 2"
echo "----------"
diff test/2200909C/out2.txt <(./2200909C <test/2200909C/input2.txt)
echo "----------"
